# Generated by Django 5.2.6 on 2025-10-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.DecimalField(decimal_places=2, default=1, help_text='Number of servings this recipe produces', max_digits=10)),
                ('preparation_time', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('cooking_time', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Cooking instructions')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='restaurant.branch')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='restaurant.product')),
            ],
            options={
                'verbose_name': 'Recipe (BOM)',
                'verbose_name_plural': 'Recipes (BOM)',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity needed per serving in base units (g, ml, pcs)', max_digits=10)),
                ('unit', models.CharField(help_text='Base unit: gram, ml, piece, etc', max_length=50)),
                ('notes', models.CharField(blank=True, help_text="e.g., 'finely chopped', 'room temperature'", max_length=200)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='restaurant.inventory')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant.recipe')),
            ],
            options={
                'ordering': ['recipe', 'inventory_item__name'],
                'unique_together': {('recipe', 'inventory_item')},
            },
        ),
    ]
