# Generated by Django 5.2.6 on 2025-10-20 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_add_void_fields_to_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='earliest_expiry_date',
            field=models.DateField(blank=True, help_text='Earliest expiry date among all active batches for this item', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='has_expiring_items',
            field=models.BooleanField(default=False, help_text='Flag indicating if any batches are expiring within 30 days'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, help_text='Current quantity available in this batch', max_digits=10)),
                ('original_quantity', models.DecimalField(decimal_places=2, help_text='Original quantity when batch was received', max_digits=10)),
                ('expiry_date', models.DateField(db_index=True, help_text='Date when this batch expires')),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('DISPOSED', 'Disposed')], db_index=True, default='ACTIVE', max_length=20)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('disposal_method', models.CharField(blank=True, help_text='Method of disposal: WASTE, DONATED, RETURNED', max_length=50)),
                ('disposal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_batches', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='restaurant.inventory')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='restaurant.purchaseorder')),
            ],
            options={
                'verbose_name': 'Inventory Batch',
                'verbose_name_plural': 'Inventory Batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
    ]
