# Generated by Django 5.2.6 on 2025-11-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_customer_customerfeedback_membershiptierbenefit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='sessionauditlog',
            name='event_type',
            field=models.CharField(choices=[('SESSION_OPENED', 'Session Opened'), ('SESSION_CLOSED', 'Session Closed'), ('OVERRIDE_APPLIED', 'Manager Override Applied'), ('SCHEDULE_WARNING', 'Schedule Warning'), ('CASH_DISCREPANCY', 'Cash Discrepancy Detected'), ('PAYMENT_VOIDED', 'Payment Voided')], max_length=50),
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=11.0, help_text='Tax percentage (e.g., 11.00 for 11%)', max_digits=5)),
                ('currency', models.CharField(default='IDR', help_text='Currency code (e.g., IDR, USD)', max_length=3)),
                ('timezone', models.CharField(default='Asia/Jakarta', help_text='Timezone for the restaurant', max_length=50)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('new_order_alerts', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('daily_reports', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('data_retention_days', models.IntegerField(default=365, help_text='Number of days to retain data')),
                ('enable_audit_log', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('kitchen_printer_ip', models.CharField(blank=True, help_text='IP address of kitchen printer', max_length=15)),
                ('receipt_printer_ip', models.CharField(blank=True, help_text='IP address of receipt printer', max_length=15)),
                ('enable_auto_print', models.BooleanField(default=True)),
                ('print_receipts', models.BooleanField(default=True)),
                ('print_kitchen_orders', models.BooleanField(default=True)),
                ('min_password_length', models.IntegerField(default=8)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('require_special_chars', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('enable_two_factor', models.BooleanField(default=False)),
                ('enable_ip_restriction', models.BooleanField(default=False)),
                ('max_login_attempts', models.IntegerField(default=3)),
                ('enable_data_encryption', models.BooleanField(default=True)),
                ('anonymize_logs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
