# Generated by Django 5.2.6 on 2025-11-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_alter_product_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Restaurant serial number', max_length=50),
        ),
    ]
