# Generated by Django 5.2.6 on 2025-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_orderitem_quantity_served_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('WAREHOUSE', 'Gudang'), ('KITCHEN', 'Dapur'), ('BAR', 'Bar')], default='WAREHOUSE', help_text='Storage location: Warehouse for raw materials, Kitchen for ready-to-use items', max_length=20),
        ),
    ]
