# Generated by Django 5.2.6 on 2025-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='bar_printer_ip',
            field=models.CharField(blank=True, help_text='IP address of bar printer', max_length=15),
        ),
    ]
