# Generated by Django 5.2.6 on 2025-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_add_staff_session_and_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='breakage_count',
            field=models.IntegerField(default=0, help_text='Total count of breakage/loss (for durable utilities)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food Ingredient'), ('BEVERAGE', 'Beverage'), ('CLEANING', 'Cleaning Supplies'), ('SERVING', 'Serving Items'), ('PACKAGING', 'Packaging'), ('KITCHEN_TOOLS', 'Kitchen Tools'), ('DISPOSABLES', 'Disposables'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], db_index=True, default='FOOD', help_text='Category of inventory item', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_durable',
            field=models.BooleanField(default=False, help_text='Is this a durable item (e.g., plates, cutlery)?'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('CONSUMABLE', 'Consumable (Food/Beverage)'), ('UTILITY', 'Utility (Non-food)'), ('EQUIPMENT', 'Equipment (Durable)')], db_index=True, default='CONSUMABLE', help_text='Type of inventory item', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_restock_date',
            field=models.DateField(blank=True, help_text='Date of last stock replenishment', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lifespan_days',
            field=models.IntegerField(blank=True, help_text='Expected lifespan in days (for durable items)', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='par_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optimal stock level to maintain (for utilities)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('WASTE', 'Waste'), ('TRANSFER', 'Transfer'), ('BREAKAGE', 'Breakage')], max_length=10),
        ),
    ]
