# Generated by Django 5.2.7 on 2025-11-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_add_promo_fields_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_room_charge',
            field=models.BooleanField(default=False, help_text='Charge to hotel guest room'),
        ),
        migrations.AddField(
            model_name='payment',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True, help_text='Hotel room number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=200, null=True, help_text='Hotel guest name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hotel_reservation_id',
            field=models.IntegerField(blank=True, null=True, help_text='Reference to hotel reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('CASH', 'Cash'),
                    ('CARD', 'Credit/Debit Card'),
                    ('MOBILE', 'Mobile Payment'),
                    ('ROOM_CHARGE', 'Room Charge'),
                    ('OTHER', 'Other'),
                ],
                max_length=20
            ),
        ),
    ]
