module.exports = {
  apps: [
    // ========== RESTO SYSTEM ==========
    {
      name: 'resto-backend',
      cwd: 'C:/ladapala/resto/backend',
      script: '.venv/Scripts/python.exe',
      args: 'manage.py runserver 0.0.0.0:8000 --noreload',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      exec_mode: 'fork',
      env: {
        PYTHONUNBUFFERED: '1',
        DJANGO_SETTINGS_MODULE: 'core.settings',
        PORT: '8000',
      },
      error_file: 'C:/ladapala/logs/resto/backend-error.log',
      out_file: 'C:/ladapala/logs/resto/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'resto-frontend',
      cwd: 'C:/ladapala/resto/frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000 -H 0.0.0.0',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
      error_file: 'C:/ladapala/logs/resto/frontend-error.log',
      out_file: 'C:/ladapala/logs/resto/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },

    // ========== HOTELBASE SYSTEM ==========
    {
      name: 'hotel-backend',
      cwd: 'C:/ladapala/hotelbase/backend',
      script: '.venv/Scripts/python.exe',
      args: 'manage.py runserver 0.0.0.0:8001 --noreload',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      exec_mode: 'fork',
      env: {
        PYTHONUNBUFFERED: '1',
        DJANGO_SETTINGS_MODULE: 'core.settings',
        PORT: '8001',
      },
      error_file: 'C:/ladapala/logs/hotelbase/backend-error.log',
      out_file: 'C:/ladapala/logs/hotelbase/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
    {
      name: 'hotel-frontend',
      cwd: 'C:/ladapala/hotelbase/frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3001 -H 0.0.0.0',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
      },
      error_file: 'C:/ladapala/logs/hotelbase/frontend-error.log',
      out_file: 'C:/ladapala/logs/hotelbase/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
    },
  ],
};
