# Generated by Django 5.2.6 on 2025-10-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_sessions', to='restaurant.branch')),
                ('cashier', models.ForeignKey(limit_choices_to={'role': 'CASHIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_sessions', to='restaurant.staff')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to='restaurant.staff')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='cashier_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='restaurant.cashiersession'),
        ),
    ]
