# Generated by Django 5.2.6 on 2025-10-16 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_cashiersession_payment_cashier_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiersession',
            name='override_by',
            field=models.ForeignKey(blank=True, help_text='Manager who authorized session without schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_overrides', to='restaurant.staff'),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Reason for override'),
        ),
        migrations.CreateModel(
            name='SessionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SESSION_OPENED', 'Session Opened'), ('SESSION_CLOSED', 'Session Closed'), ('OVERRIDE_APPLIED', 'Manager Override Applied'), ('SCHEDULE_WARNING', 'Schedule Warning'), ('CASH_DISCREPANCY', 'Cash Discrepancy Detected')], max_length=50)),
                ('event_data', models.JSONField(blank=True, help_text='Additional event details', null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.staff')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='restaurant.cashiersession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
