# Generated by Django 5.2.6 on 2025-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_recipe_recipeingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
