# Generated by Django 5.2.6 on 2025-10-18 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_inventory_options_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
