# Generated by Django 5.2.6 on 2025-11-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_add_utility_inventory_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False, help_text='Is this item on promotion?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_seasonal',
            field=models.BooleanField(default=False, help_text='Is this a seasonal menu item?'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_label',
            field=models.CharField(blank=True, help_text="Custom promo label (e.g. 'Buy 1 Get 1', 'Limited Time')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promotional price (overrides discount_percentage if set)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Promo valid from date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Promo valid until date', null=True),
        ),
    ]
