# Generated by Django 5.2.6 on 2025-12-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_barorder_barorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_split_bill',
            field=models.BooleanField(default=False, help_text='Whether this is part of a split bill'),
        ),
        migrations.AddField(
            model_name='order',
            name='merged_from_tables',
            field=models.JSONField(blank=True, default=list, help_text='List of table IDs that were merged into this table'),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, help_text='Original order if this is a split', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_orders', to='restaurant.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='split_number',
            field=models.IntegerField(blank=True, help_text='Split number (1, 2, 3, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='split_total',
            field=models.IntegerField(blank=True, help_text='Total number of splits', null=True),
        ),
    ]
