# Generated by Django 5.0.1 on 2025-09-28 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specializations', models.JSONField(default=list)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Elevator', 'Elevator'), ('IT/Network', 'IT/Network'), ('General', 'General'), ('Security', 'Security')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('source', models.CharField(choices=[('GUEST_REQUEST', 'Guest Request'), ('STAFF_REPORT', 'Staff Report'), ('PREVENTIVE', 'Preventive Maintenance'), ('INSPECTION', 'Inspection'), ('EMERGENCY', 'Emergency')], default='STAFF_REPORT', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assigned_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('technician_notes', models.TextField(blank=True, null=True)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_satisfaction', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.guest')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
