# Generated by Django 5.2.7 on 2025-11-16 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('HOTEL_HOUSEKEEPING', 'Hotel - Housekeeping'), ('HOTEL_FRONT_DESK', 'Hotel - Front Desk'), ('HOTEL_MAINTENANCE', 'Hotel - Maintenance'), ('HOTEL_LAUNDRY', 'Hotel - Laundry'), ('HOTEL_FB', 'Hotel - F&B'), ('HOTEL_ENGINEERING', 'Hotel - Engineering'), ('RESTO_KITCHEN', 'Restaurant - Kitchen'), ('RESTO_BAR', 'Restaurant - Bar'), ('RESTO_SERVICE', 'Restaurant - Service/Waitstaff'), ('RESTO_STORAGE', 'Restaurant - Dry Storage'), ('ADMIN', 'Administration')], max_length=30)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current buffer stock', max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Minimum buffer level', max_digits=10)),
                ('max_stock', models.DecimalField(decimal_places=2, default=100, help_text='Maximum buffer capacity', max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Storage location in department', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Buffer',
                'verbose_name_plural': 'Department Buffers',
                'ordering': ['department', 'warehouse_item__name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Supplier rating (0-5)', max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='warehouse.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('for_hotel', models.BooleanField(default=True)),
                ('for_restaurant', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='warehouse.warehousecategory')),
            ],
            options={
                'verbose_name': 'Warehouse Category',
                'verbose_name_plural': 'Warehouse Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SKU/Item code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('DURABLE', 'Durable Goods'), ('PERISHABLE', 'Perishable'), ('AMENITY', 'Guest Amenity'), ('LINEN', 'Linen & Textile'), ('CLEANING', 'Cleaning Supplies'), ('KITCHEN', 'Kitchen Supplies'), ('BAR', 'Bar Supplies'), ('MAINTENANCE', 'Maintenance Supplies'), ('OFFICE', 'Office Supplies')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Current warehouse stock', max_digits=10)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock level', max_digits=10)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stock level', max_digits=10, null=True)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, help_text='Reorder when stock reaches this', max_digits=10)),
                ('unit_of_measure', models.CharField(choices=[('PIECE', 'Piece'), ('KG', 'Kilogram'), ('LITER', 'Liter'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('PACK', 'Pack'), ('METER', 'Meter'), ('SET', 'Set'), ('DOZEN', 'Dozen'), ('GALLON', 'Gallon')], default='PIECE', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Moving average cost', max_digits=10)),
                ('lead_time_days', models.IntegerField(default=7, help_text='Supplier lead time in days')),
                ('is_active', models.BooleanField(default=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='warehouse.warehousecategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_items', to='warehouse.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('transfer_type', models.CharField(choices=[('WAREHOUSE_TO_DEPT', 'Warehouse to Department'), ('DEPT_TO_DEPT', 'Department to Department'), ('DEPT_TO_WAREHOUSE', 'Department Return to Warehouse')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('from_warehouse', models.BooleanField(default=True, help_text='Transfer from main warehouse')),
                ('from_department', models.CharField(blank=True, choices=[('HOTEL_HOUSEKEEPING', 'Hotel - Housekeeping'), ('HOTEL_FRONT_DESK', 'Hotel - Front Desk'), ('HOTEL_MAINTENANCE', 'Hotel - Maintenance'), ('HOTEL_LAUNDRY', 'Hotel - Laundry'), ('HOTEL_FB', 'Hotel - F&B'), ('HOTEL_ENGINEERING', 'Hotel - Engineering'), ('RESTO_KITCHEN', 'Restaurant - Kitchen'), ('RESTO_BAR', 'Restaurant - Bar'), ('RESTO_SERVICE', 'Restaurant - Service/Waitstaff'), ('RESTO_STORAGE', 'Restaurant - Dry Storage'), ('ADMIN', 'Administration')], max_length=30, null=True)),
                ('to_department', models.CharField(choices=[('HOTEL_HOUSEKEEPING', 'Hotel - Housekeeping'), ('HOTEL_FRONT_DESK', 'Hotel - Front Desk'), ('HOTEL_MAINTENANCE', 'Hotel - Maintenance'), ('HOTEL_LAUNDRY', 'Hotel - Laundry'), ('HOTEL_FB', 'Hotel - F&B'), ('HOTEL_ENGINEERING', 'Hotel - Engineering'), ('RESTO_KITCHEN', 'Restaurant - Kitchen'), ('RESTO_BAR', 'Restaurant - Bar'), ('RESTO_SERVICE', 'Restaurant - Service/Waitstaff'), ('RESTO_STORAGE', 'Restaurant - Dry Storage'), ('ADMIN', 'Administration')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for transfer', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='warehouse.warehouseitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('adjustment_type', models.CharField(choices=[('DAMAGE', 'Damaged'), ('LOSS', 'Lost/Stolen'), ('FOUND', 'Found/Surplus'), ('CORRECTION', 'Stock Count Correction'), ('EXPIRED', 'Expired'), ('RETURN', 'Return to Supplier')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for increase, negative for decrease', max_digits=10)),
                ('reason', models.TextField(help_text='Reason for adjustment')),
                ('adjustment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department_buffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='warehouse.departmentbuffer')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='warehouse.warehouseitem')),
            ],
            options={
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.purchaseorder')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseitem')),
            ],
            options={
                'ordering': ['warehouse_item__name'],
            },
        ),
        migrations.AddField(
            model_name='departmentbuffer',
            name='warehouse_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_buffers', to='warehouse.warehouseitem'),
        ),
        migrations.AddIndex(
            model_name='warehouseitem',
            index=models.Index(fields=['code'], name='warehouse_w_code_fd099d_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseitem',
            index=models.Index(fields=['category', 'item_type'], name='warehouse_w_categor_effb79_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', '-created_at'], name='warehouse_s_status_5b5266_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_department'], name='warehouse_s_to_depa_d8ee81_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentbuffer',
            index=models.Index(fields=['department'], name='warehouse_d_departm_db6efa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentbuffer',
            unique_together={('department', 'warehouse_item')},
        ),
    ]
