# Generated by Django 5.2.7 on 2025-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='allergies',
            field=models.TextField(blank=True, help_text='Food allergies, medical conditions', null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='preferences',
            field=models.TextField(blank=True, help_text='Room preferences, bed type, floor, etc.', null=True),
        ),
    ]
