# Generated by Django 5.2.7 on 2025-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_migrate_inventory_category_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitycategory',
            name='display_name',
            field=models.CharField(help_text='Display name shown to users', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenitycategory',
            name='name',
            field=models.CharField(help_text='Unique category identifier (e.g., TOILETRIES, FOOD_BEVERAGE)', max_length=50, unique=True),
        ),
    ]
