# Generated by Django 5.2.7 on 2025-11-04 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_payment_discount_payment_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Assigned at check-in', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
