# Generated by Django 5.2.7 on 2025-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_update_loyalty_points_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PARTIAL', 'Partial Payment'), ('FULL', 'Full Payment'), ('BALANCE', 'Balance Payment')], default='FULL', help_text='Type of payment: deposit, partial, or full payment', max_length=20),
        ),
    ]
