# Generated by Django 5.2.7 on 2025-11-15 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_alter_departmentinventory_department_lostandfound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeUpCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(help_text='Guest name', max_length=200)),
                ('call_date', models.DateField(help_text='Date of the wake up call')),
                ('call_time', models.TimeField(help_text='Time for the wake up call')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the call was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Staff who completed the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wake_up_calls_completed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Staff who created the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wake_up_calls_requested', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, help_text='Associated reservation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wake_up_calls', to='hotel.reservation')),
                ('room', models.ForeignKey(help_text='Room number for the wake up call', on_delete=django.db.models.deletion.CASCADE, related_name='wake_up_calls', to='hotel.room')),
            ],
            options={
                'ordering': ['call_date', 'call_time'],
                'indexes': [models.Index(fields=['call_date', 'call_time'], name='hotel_wakeu_call_da_2805f2_idx'), models.Index(fields=['status', 'call_date'], name='hotel_wakeu_status_0bbb50_idx'), models.Index(fields=['room', 'call_date'], name='hotel_wakeu_room_id_87649a_idx')],
            },
        ),
    ]
