# Generated by Django 5.2.7 on 2026-01-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_wakeupcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Hotel logo (recommended: 200x200px)', null=True, upload_to='settings/logos/'),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='logo_url',
            field=models.CharField(default='/logo.png', help_text='Fallback if no logo uploaded', max_length=200),
        ),
    ]
