# Generated by Django 5.2.6 on 2025-10-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_cashiersession_override_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['branch', 'location', 'name'], 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('WAREHOUSE', 'Gudang'), ('KITCHEN', 'Dapur')], default='WAREHOUSE', help_text='Storage location: Warehouse for raw materials, Kitchen for ready-to-use items', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('WASTE', 'Waste'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('branch', 'name', 'location')},
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='restaurant.branch')),
                ('from_warehouse', models.ForeignKey(limit_choices_to={'location': 'WAREHOUSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='restaurant.inventory')),
                ('to_kitchen', models.ForeignKey(limit_choices_to={'location': 'KITCHEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='restaurant.inventory')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
