# Generated by Django 5.2.6 on 2025-10-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_inventory_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms_days',
            field=models.IntegerField(default=30, help_text='Number of days for payment (e.g., 30 for Net 30)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_id',
            field=models.CharField(blank=True, help_text='NPWP or Tax ID', max_length=50),
        ),
    ]
