# Generated by Django 5.2.6 on 2025-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_add_bar_printer_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('CHEF', 'Chef'), ('KITCHEN', 'Kitchen Staff'), ('BAR', 'Bar Staff'), ('WAITRESS', 'Waitress'), ('WAREHOUSE', 'Warehouse Staff')], max_length=20),
        ),
    ]
