# Generated by Django 5.2.6 on 2025-11-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_add_chef_bar_waitress_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_taken_by',
            field=models.ForeignKey(blank=True, help_text='Waitress who took the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_taken', to='restaurant.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_completed_at',
            field=models.DateTimeField(blank=True, help_text='When marked READY', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_started_at',
            field=models.DateTimeField(blank=True, help_text='When chef/bar claimed it', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prepared_by',
            field=models.ForeignKey(blank=True, help_text='Chef/Bar staff who prepared the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_prepared', to='restaurant.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='served_at',
            field=models.DateTimeField(blank=True, help_text='When marked COMPLETED', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='served_by',
            field=models.ForeignKey(blank=True, help_text='Waitress who served the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_served', to='restaurant.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='taken_at',
            field=models.DateTimeField(blank=True, help_text='When order was taken', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prepared_by',
            field=models.ForeignKey(blank=True, help_text='Chef/Bar staff who prepared this specific item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_items', to='restaurant.staff'),
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('override_reason', models.TextField(blank=True, help_text='Reason for override')),
                ('orders_taken_count', models.IntegerField(default=0, help_text='For waitress - orders taken')),
                ('orders_prepared_count', models.IntegerField(default=0, help_text='For kitchen/bar - orders prepared')),
                ('orders_served_count', models.IntegerField(default=0, help_text='For waitress - orders served')),
                ('items_prepared_count', models.IntegerField(default=0, help_text='For kitchen/bar - individual items prepared')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_sessions', to='restaurant.branch')),
                ('override_by', models.ForeignKey(blank=True, help_text='Manager who authorized session without schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_session_overrides', to='restaurant.staff')),
                ('schedule', models.ForeignKey(blank=True, help_text='Link to schedule for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_sessions', to='restaurant.schedule')),
                ('staff', models.ForeignKey(help_text='Staff member (WAITRESS, BAR, CHEF, or KITCHEN)', on_delete=django.db.models.deletion.CASCADE, related_name='staff_sessions', to='restaurant.staff')),
            ],
            options={
                'verbose_name': 'Staff Session',
                'verbose_name_plural': 'Staff Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='waitress_session',
            field=models.ForeignKey(blank=True, help_text='Waitress session when order was taken', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_taken_in_session', to='restaurant.staffsession'),
        ),
        migrations.AddIndex(
            model_name='staffsession',
            index=models.Index(fields=['staff', 'status'], name='restaurant__staff_i_47bce0_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsession',
            index=models.Index(fields=['branch', 'opened_at'], name='restaurant__branch__95cd09_idx'),
        ),
    ]
