# Generated by Django 5.2.6 on 2025-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Moving average cost per unit, updated when PO items are received', max_digits=10),
        ),
    ]
