# Generated by Django 5.2.7 on 2025-10-26 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_housekeepingtask_amenityusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('EARLY_CHECKIN', 'Early Check-in'), ('LATE_CHECKOUT', 'Late Check-out'), ('MINIBAR', 'Minibar'), ('LAUNDRY', 'Laundry'), ('ROOM_SERVICE', 'Room Service'), ('PARKING', 'Parking'), ('EXTRA_BED', 'Extra Bed'), ('BREAKFAST', 'Breakfast'), ('DAMAGE', 'Damage Charge'), ('PHONE', 'Phone Calls'), ('INTERNET', 'Internet/WiFi'), ('SPA', 'Spa Services'), ('AIRPORT_TRANSFER', 'Airport Transfer'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='hotel.reservation')),
            ],
            options={
                'verbose_name': 'Additional Charge',
                'verbose_name_plural': 'Additional Charges',
                'ordering': ['-charged_at'],
            },
        ),
    ]
