# Generated by Django 5.2.7 on 2025-10-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_additionalcharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housekeepingtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Housekeeping Task', 'verbose_name_plural': 'Housekeeping Tasks'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['check_in_date']},
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_types/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotel.roomtype')),
            ],
            options={
                'verbose_name': 'Room Type Image',
                'verbose_name_plural': 'Room Type Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
