# Generated by Django 5.2.7 on 2025-10-31 09:30

from django.db import migrations, models


def copy_display_name_to_name(apps, schema_editor):
    """Copy display_name values to name field before removing display_name"""
    AmenityCategory = apps.get_model('hotel', 'AmenityCategory')
    for category in AmenityCategory.objects.all():
        if hasattr(category, 'display_name') and category.display_name:
            category.name = category.display_name
            category.save(update_fields=['name'])


def reverse_migration(apps, schema_editor):
    """Reverse: copy name back to display_name"""
    AmenityCategory = apps.get_model('hotel', 'AmenityCategory')
    for category in AmenityCategory.objects.all():
        category.display_name = category.name
        category.save(update_fields=['display_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_remove_category_choices'),
    ]

    operations = [
        # First, copy display_name to name
        migrations.RunPython(copy_display_name_to_name, reverse_migration),

        # Then update Meta options
        migrations.AlterModelOptions(
            name='amenitycategory',
            options={'ordering': ['name'], 'verbose_name': 'Amenity Category', 'verbose_name_plural': 'Amenity Categories'},
        ),

        # Remove display_name field
        migrations.RemoveField(
            model_name='amenitycategory',
            name='display_name',
        ),

        # Update name field to allow longer values
        migrations.AlterField(
            model_name='amenitycategory',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Toiletries & Bath, Food & Beverage)', max_length=100, unique=True),
        ),
    ]
