# Generated by Django 5.2.7 on 2025-11-02 09:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_roomtype_room_category_roomtype_seating_arrangement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('BRONZE', 'Bronze Package'), ('SILVER', 'Silver Package'), ('GOLD', 'Gold Package'), ('PLATINUM', 'Platinum Package'), ('CUSTOM', 'Custom Package')], max_length=20)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('includes_venue', models.BooleanField(default=True)),
                ('includes_sound_system', models.BooleanField(default=False)),
                ('includes_projector', models.BooleanField(default=False)),
                ('includes_led_screen', models.BooleanField(default=False)),
                ('includes_lighting', models.BooleanField(default=False)),
                ('includes_ac', models.BooleanField(default=True)),
                ('includes_tables_chairs', models.BooleanField(default=True)),
                ('includes_decoration', models.BooleanField(default=False)),
                ('includes_parking', models.BooleanField(default=False)),
                ('max_hours', models.PositiveIntegerField(default=8, help_text='Maximum hours included')),
                ('additional_hour_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='FoodPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('COFFEE_BREAK', 'Coffee Break'), ('COCKTAIL', 'Cocktail Party'), ('FULL_BOARD', 'Full Board')], max_length=20)),
                ('description', models.TextField()),
                ('price_per_pax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_pax', models.PositiveIntegerField(default=50)),
                ('menu_items', models.TextField(help_text='List of menu items included')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'price_per_pax'],
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('WEDDING', 'Wedding Reception'), ('CONFERENCE', 'Conference/Seminar'), ('MEETING', 'Business Meeting'), ('BIRTHDAY', 'Birthday Party'), ('ANNIVERSARY', 'Anniversary'), ('CORPORATE', 'Corporate Event'), ('EXHIBITION', 'Exhibition/Trade Show'), ('WORKSHOP', 'Workshop/Training'), ('OTHER', 'Other Event')], max_length=20)),
                ('organizer_name', models.CharField(blank=True, help_text='If different from guest', max_length=200)),
                ('organizer_phone', models.CharField(blank=True, max_length=20)),
                ('organizer_email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.CharField(blank=True, help_text='Company/Organization name', max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('setup_time', models.TimeField(blank=True, help_text='Setup start time', null=True)),
                ('expected_pax', models.PositiveIntegerField(help_text='Expected number of guests')),
                ('confirmed_pax', models.PositiveIntegerField(blank=True, help_text='Final confirmed PAX', null=True)),
                ('venue_price', models.DecimalField(decimal_places=2, help_text='Base venue package price', max_digits=12)),
                ('food_price', models.DecimalField(decimal_places=2, default=0, help_text='Food total (PAX × price_per_pax)', max_digits=12)),
                ('equipment_price', models.DecimalField(decimal_places=2, default=0, help_text='Additional equipment', max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, help_text='Decoration, parking, etc.', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='11% tax', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment_percentage', models.DecimalField(decimal_places=2, default=30, help_text='Percentage for down payment', max_digits=5)),
                ('down_payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment_paid', models.BooleanField(default=False)),
                ('full_payment_paid', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_notes', models.TextField(blank=True, help_text='Additional notes for invoice', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_bookings_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='hotel.guest')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_bookings', to='hotel.room')),
                ('venue_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.eventpackage')),
                ('food_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.foodpackage')),
            ],
            options={
                'ordering': ['-event_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('EQUIPMENT', 'Equipment'), ('DECORATION', 'Decoration'), ('STAFF', 'Additional Staff'), ('SERVICE', 'Service'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='hotel.eventbooking')),
            ],
        ),
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('payment_type', models.CharField(choices=[('DOWN_PAYMENT', 'Down Payment'), ('FULL_PAYMENT', 'Full Payment'), ('ADDITIONAL', 'Additional Charges')], max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('CARD', 'Credit/Debit Card'), ('EDC', 'EDC')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank transfer reference, card approval code, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.eventbooking')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
