# Generated by Django 5.2.7 on 2025-11-03 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_eventpackage_foodpackage_eventbooking_eventaddon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opname_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('opname_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('location', models.CharField(default='Main Warehouse', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items_counted', models.PositiveIntegerField(default=0)),
                ('total_discrepancies', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opnames_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opnames_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Opname',
                'verbose_name_plural': 'Stock Opnames',
                'ordering': ['-opname_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOpnameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_stock', models.PositiveIntegerField(help_text='Stock in system at start of opname')),
                ('counted_stock', models.PositiveIntegerField(blank=True, help_text='Physical count', null=True)),
                ('difference', models.IntegerField(default=0, help_text='Counted - System')),
                ('reason', models.TextField(blank=True, help_text='Reason for discrepancy', null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opname_items_counted', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.inventoryitem')),
                ('stock_opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotel.stockopname')),
            ],
            options={
                'ordering': ['inventory_item__name'],
                'unique_together': {('stock_opname', 'inventory_item')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('CANCEL', 'Cancelled'), ('COMPLETE', 'Completed'), ('ADJUST', 'Adjusted'), ('COUNT', 'Counted'), ('RECEIVE', 'Received')], max_length=20)),
                ('model_name', models.CharField(help_text='Model that was affected', max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the affected object')),
                ('object_repr', models.CharField(help_text='String representation of object', max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='Dictionary of changes: {"field": {"old": value, "new": value}}', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Audit Log',
                'verbose_name_plural': 'Warehouse Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='hotel_wareh_timesta_9bc700_idx'), models.Index(fields=['model_name', 'object_id'], name='hotel_wareh_model_n_12008d_idx'), models.Index(fields=['user', '-timestamp'], name='hotel_wareh_user_id_b4078d_idx'), models.Index(fields=['action_type'], name='hotel_wareh_action__579af0_idx')],
            },
        ),
    ]
