# Generated by Django 5.2.7 on 2025-11-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_reservation_room_type_alter_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('ktp', 'KTP (Indonesian ID)'), ('kitas', 'KITAS'), ('driving_license', 'Driving License'), ('other', 'Other')], default='passport', max_length=20),
        ),
    ]
