# Generated by Django 5.2.7 on 2025-11-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0040_add_guest_rating_and_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='from_department',
            field=models.CharField(blank=True, help_text='Source department (if applicable)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_department',
            field=models.CharField(blank=True, help_text='Destination department (if applicable)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase Order'), ('ADJUSTMENT', 'Stock Adjustment'), ('USAGE', 'Usage'), ('RETURN', 'Return'), ('WAREHOUSE_TO_DEPARTMENT', 'Warehouse to Department'), ('DEPARTMENT_TO_GUEST', 'Department to Guest'), ('DEPARTMENT_TO_WAREHOUSE', 'Department to Warehouse'), ('DEPARTMENT_TO_DEPARTMENT', 'Department to Department')], max_length=30),
        ),
        migrations.CreateModel(
            name='DepartmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('F&B', 'Food & Beverage'), ('MAINTENANCE', 'Maintenance'), ('FRONT_DESK', 'Front Desk'), ('ENGINEERING', 'Engineering'), ('LAUNDRY', 'Laundry')], max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current buffer quantity', max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Minimum buffer level', max_digits=10)),
                ('max_stock', models.DecimalField(decimal_places=2, default=100, help_text='Maximum buffer capacity', max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Physical storage location in department', max_length=100, null=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_buffers', to='hotel.inventoryitem')),
            ],
            options={
                'verbose_name': 'Department Inventory',
                'verbose_name_plural': 'Department Inventories',
                'ordering': ['department', 'inventory_item__name'],
                'unique_together': {('department', 'inventory_item')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='department_inventory',
            field=models.ForeignKey(blank=True, help_text='Related department inventory record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='hotel.departmentinventory'),
        ),
    ]
