# Generated by Django 5.2.7 on 2025-10-29 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address_user_avatar_user_bio_user_date_of_birth_and_more'),
    ]

    operations = [
        # Remove duplicate fields from Employee (these are now accessed via user relationship)
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        # Add emergency_relationship field
        migrations.AddField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Make user field required (non-nullable)
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
