# Generated by Django 5.2.7 on 2025-10-26 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('task_type', models.CharField(choices=[('CHECKOUT_CLEANING', 'Checkout Cleaning'), ('STAYOVER_CLEANING', 'Stayover Cleaning'), ('DEEP_CLEANING', 'Deep Cleaning'), ('TURNDOWN_SERVICE', 'Turndown Service'), ('MAINTENANCE', 'Maintenance')], default='CHECKOUT_CLEANING', max_length=30)),
                ('status', models.CharField(choices=[('DIRTY', 'Needs Cleaning'), ('CLEANING', 'In Progress'), ('INSPECTING', 'Inspection'), ('CLEAN', 'Ready'), ('OUT_OF_ORDER', 'Out of Order'), ('MAINTENANCE', 'Maintenance')], default='DIRTY', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('scheduled_date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('guest_checkout', models.DateTimeField(blank=True, null=True)),
                ('next_guest_checkin', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('guest_requests', models.JSONField(blank=True, default=list)),
                ('maintenance_issues', models.JSONField(blank=True, default=list)),
                ('inspection_passed', models.BooleanField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('inspection_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Housekeeping Task',
                'verbose_name_plural': 'Housekeeping Tasks',
                'ordering': ['-scheduled_date', '-priority', 'room__number'],
            },
        ),
        migrations.CreateModel(
            name='AmenityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='hotel.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('housekeeping_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_usages', to='hotel.housekeepingtask')),
            ],
            options={
                'verbose_name': 'Amenity Usage',
                'verbose_name_plural': 'Amenity Usages',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['status', 'scheduled_date'], name='hotel_house_status_02f211_idx'),
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['assigned_to', 'status'], name='hotel_house_assigne_e489c6_idx'),
        ),
        migrations.AddIndex(
            model_name='housekeepingtask',
            index=models.Index(fields=['room', 'scheduled_date'], name='hotel_house_room_id_7c2abd_idx'),
        ),
        migrations.AddIndex(
            model_name='amenityusage',
            index=models.Index(fields=['housekeeping_task', 'inventory_item'], name='hotel_ameni_houseke_2de122_idx'),
        ),
        migrations.AddIndex(
            model_name='amenityusage',
            index=models.Index(fields=['recorded_at'], name='hotel_ameni_recorde_ffcac7_idx'),
        ),
    ]
