# Generated by Django 5.2.7 on 2025-10-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_amenityrequest_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under Maintenance'), ('CLEANING', 'Cleaning'), ('OUT_OF_ORDER', 'Out of Order')], default='AVAILABLE', max_length=20),
        ),
    ]
