# Generated by Django 5.2.7 on 2025-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_remove_display_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_team',
            field=models.CharField(blank=True, choices=[('ENGINEERING', 'Engineering/Maintenance'), ('HOUSEKEEPING', 'Cleaning/Housekeeping'), ('FRONT_DESK', 'Front Desk'), ('FOOD_BEVERAGE', 'Food & Beverage'), ('MANAGEMENT', 'Management')], max_length=20, null=True),
        ),
    ]
