# Generated by Django 5.2.7 on 2025-10-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_complaint_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingtask',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hotel.complaint'),
        ),
        migrations.AlterField(
            model_name='housekeepingtask',
            name='task_type',
            field=models.CharField(choices=[('CHECKOUT_CLEANING', 'Checkout Cleaning'), ('STAYOVER_CLEANING', 'Stayover Cleaning'), ('DEEP_CLEANING', 'Deep Cleaning'), ('TURNDOWN_SERVICE', 'Turndown Service'), ('MAINTENANCE', 'Maintenance'), ('COMPLAINT', 'Guest Complaint')], default='CHECKOUT_CLEANING', max_length=30),
        ),
    ]
