# Generated by Django 5.2.7 on 2025-11-01 12:15

import apps.hotel.models.housekeeping
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_hotelsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeepingtask',
            name='scheduled_date',
            field=models.DateField(default=apps.hotel.models.housekeeping.get_today),
        ),
    ]
