# Generated by Django 5.2.7 on 2025-11-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_cleaningtemplate_cleaningtemplateitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed_configuration',
            field=models.CharField(choices=[('1_KING', '1 King Bed'), ('2_TWIN', '2 Twin Beds'), ('1_KING_SOFA', '1 King Bed + Sofa Bed'), ('1_KING_2_TWIN', '1 King Bed + 2 Twin Beds'), ('2_QUEEN', '2 Queen Beds'), ('1_QUEEN', '1 Queen Bed'), ('1_QUEEN_SOFA', '1 Queen Bed + Sofa Bed')], default='1_KING', help_text='Bed type configuration for this room', max_length=20),
        ),
    ]
