# Generated by Django 5.2.7 on 2025-11-02 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_roomtype_bed_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_category',
            field=models.CharField(choices=[('GUEST_ROOM', 'Guest Room'), ('EVENT_SPACE', 'Event Space (Ballroom/Meeting Room)')], default='GUEST_ROOM', help_text='Type of room: Guest Room or Event Space', max_length=20),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='seating_arrangement',
            field=models.CharField(blank=True, choices=[('THEATER', 'Theater Style'), ('CLASSROOM', 'Classroom Style'), ('BANQUET', 'Banquet/Round Tables'), ('U_SHAPE', 'U-Shape'), ('BOARDROOM', 'Boardroom'), ('COCKTAIL', 'Cocktail/Standing'), ('MIXED', 'Mixed Arrangement')], help_text='Seating arrangement (only for Event Spaces)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bed_configuration',
            field=models.CharField(blank=True, choices=[('1_KING', '1 King Bed'), ('2_TWIN', '2 Twin Beds'), ('1_KING_SOFA', '1 King Bed + Sofa Bed'), ('1_KING_2_TWIN', '1 King Bed + 2 Twin Beds'), ('2_QUEEN', '2 Queen Beds'), ('1_QUEEN', '1 Queen Bed'), ('1_QUEEN_SOFA', '1 Queen Bed + Sofa Bed'), ('N/A', 'N/A (Event Space)')], default='1_KING', help_text='Bed type (only for Guest Rooms)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.PositiveIntegerField(help_text='Max guests for guest rooms, or max capacity for event spaces', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
