# Generated by Django 5.2.7 on 2025-11-03 23:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_loyaltyprogram_discount_guestloyaltypoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hotel.discount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount discounted by automatic discount', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='loyalty_points_earned',
            field=models.IntegerField(default=0, help_text='Points earned from this payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='loyalty_points_redeemed',
            field=models.IntegerField(default=0, help_text='Number of loyalty points redeemed'),
        ),
        migrations.AddField(
            model_name='payment',
            name='loyalty_points_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash value of redeemed points', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before discounts', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hotel.voucher'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount discounted by voucher', max_digits=12),
        ),
    ]
