# Generated by Django 5.2.7 on 2025-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_alter_guest_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points_per_rupiah',
            field=models.DecimalField(decimal_places=4, default=0.001, help_text='Points earned per Rupiah spent (e.g., 0.001 = 1 point per 1000 Rupiah)', max_digits=10),
        ),
    ]
