# Generated by Django 5.2.7 on 2025-11-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_add_payment_type_to_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
