# Generated by Django 5.2.7 on 2025-11-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_alter_loyaltytransaction_reference_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='loyalty_points_earned',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='loyalty_points_redeemed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='loyalty_points_value',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='voucher_discount',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Guest rating from 1-5 stars', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_review',
            field=models.TextField(blank=True, help_text='Guest written review/feedback', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
