# Generated by Django 5.2.7 on 2025-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_add_department_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinventory',
            name='department',
            field=models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('F&B', 'Food & Beverage'), ('KITCHEN', 'Kitchen'), ('BAR', 'Bar'), ('MAINTENANCE', 'Maintenance'), ('FRONT_DESK', 'Front Desk'), ('ENGINEERING', 'Engineering'), ('LAUNDRY', 'Laundry')], max_length=20),
        ),
    ]
