# Generated by Django 5.2.7 on 2025-11-16 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_wakeupcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('SET', 'Sets'), ('BOX', 'Boxes'), ('ROLL', 'Rolls'), ('METER', 'Meters'), ('LITER', 'Liters'), ('KG', 'Kilograms')], default='PCS', max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('minimum_stock', models.IntegerField(default=5, help_text='Minimum stock level before reorder')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Warehouse location/shelf', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse Item',
                'verbose_name_plural': 'Warehouse Items',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='parts_needed',
            field=models.JSONField(blank=True, default=list, help_text='List of parts needed with source info'),
        ),
        migrations.CreateModel(
            name='MaintenancePartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('source', models.CharField(choices=[('WAREHOUSE', 'Warehouse Stock'), ('VENDOR', 'External Vendor')], default='WAREHOUSE', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='hotel.maintenancerequest')),
                ('warehouse_item', models.ForeignKey(blank=True, help_text='Link to warehouse item if from stock', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.warehouseitem')),
            ],
            options={
                'verbose_name': 'Maintenance Part Used',
                'verbose_name_plural': 'Maintenance Parts Used',
                'ordering': ['-used_at'],
            },
        ),
    ]
