# Generated by Django 5.2.7 on 2025-11-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_unify_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_access',
            field=models.CharField(choices=[('HOTEL', 'Hotel System'), ('RESTAURANT', 'Restaurant System'), ('BOTH', 'Both Systems')], default='HOTEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('RECEPTIONIST', 'Receptionist'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('CASHIER', 'Cashier'), ('CHEF', 'Chef'), ('WAITRESS', 'Waitress'), ('BAR', 'Bar Staff'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
