# Generated by Django 5.2.7 on 2025-10-31 04:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_alter_inventoryitem_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOOD_BEVERAGE', 'Food & Beverage'), ('TOILETRIES', 'Toiletries & Bath'), ('BEVERAGE', 'Beverages'), ('LAUNDRY', 'Laundry & Cleaning'), ('TECHNOLOGY', 'Technology'), ('FLOWERS', 'Flowers & Decor'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amenity Category',
                'verbose_name_plural': 'Amenity Categories',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AmenityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=10)),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_time', models.CharField(blank=True, max_length=50, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_department', models.CharField(blank=True, max_length=100, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guest_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('guest_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_amenity_requests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='hotel.amenitycategory')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_amenity_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_amenity_requests', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenity_requests', to='hotel.guest')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenity_requests', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Amenity Request',
                'verbose_name_plural': 'Amenity Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='hotel_ameni_status_66521d_idx'), models.Index(fields=['room', 'status'], name='hotel_ameni_room_id_aed83e_idx'), models.Index(fields=['requested_at'], name='hotel_ameni_request_26f278_idx')],
            },
        ),
    ]
