# Generated by Django 5.2.7 on 2025-10-31 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_amenitycategory_amenityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenityrequest',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Link to warehouse inventory item for automatic stock deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenity_requests', to='hotel.inventoryitem'),
        ),
    ]
