# Generated by Django 5.2.7 on 2025-10-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('FOOD_BEVERAGE', 'Food & Beverage'), ('TOILETRIES', 'Toiletries & Bath'), ('BEVERAGE', 'Beverages'), ('LAUNDRY', 'Laundry & Cleaning'), ('TECHNOLOGY', 'Technology'), ('FLOWERS', 'Flowers & Decor'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
