# Generated by Django 5.2.7 on 2025-10-31 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_update_inventory_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(help_text='Category from Amenity Categories', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='hotel.amenitycategory'),
        ),
    ]
