# Generated by Django 5.2.7 on 2025-11-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_alter_housekeepingtask_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (e.g., Standard Checkout Cleaning)', max_length=100)),
                ('task_type', models.CharField(choices=[('CHECKOUT_CLEANING', 'Checkout Cleaning'), ('STAYOVER_CLEANING', 'Stayover Cleaning'), ('DEEP_CLEANING', 'Deep Cleaning'), ('TURNDOWN_SERVICE', 'Turndown Service'), ('MAINTENANCE', 'Maintenance'), ('COMPLAINT', 'Guest Complaint')], help_text='Task type this template applies to', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(blank=True, help_text='Specific room type (optional - leave blank for all room types)', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype')),
            ],
            options={
                'verbose_name': 'Cleaning Template',
                'verbose_name_plural': 'Cleaning Templates',
                'ordering': ['task_type', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Standard quantity needed')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this item is optional')),
                ('notes', models.TextField(blank=True, help_text='Special instructions for this item', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('inventory_item', models.ForeignKey(help_text='The exact inventory item needed', on_delete=django.db.models.deletion.CASCADE, to='hotel.inventoryitem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotel.cleaningtemplate')),
            ],
            options={
                'verbose_name': 'Template Item',
                'verbose_name_plural': 'Template Items',
                'ordering': ['sort_order', 'inventory_item__name'],
            },
        ),
        migrations.AddIndex(
            model_name='cleaningtemplate',
            index=models.Index(fields=['task_type', 'is_active'], name='hotel_clean_task_ty_1b9462_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cleaningtemplateitem',
            unique_together={('template', 'inventory_item')},
        ),
    ]
