# Generated by Django 5.2.7 on 2025-11-03 16:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_stockopname_stockopnameitem_warehouseauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hotel Rewards', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points_per_rupiah', models.DecimalField(decimal_places=2, default=1, help_text='Points earned per Rupiah spent', max_digits=10)),
                ('rupiah_per_point', models.DecimalField(decimal_places=2, default=100, help_text='Rupiah value per point when redeeming', max_digits=10)),
                ('min_points_to_redeem', models.IntegerField(default=100, help_text='Minimum points required to redeem')),
                ('points_expiry_months', models.IntegerField(default=12, help_text='Months until points expire (0 = never expire)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Programs',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('EARLY_BIRD', 'Early Bird Discount'), ('LAST_MINUTE', 'Last Minute Deal'), ('LONG_STAY', 'Long Stay Discount'), ('SEASONAL', 'Seasonal Discount'), ('MEMBERSHIP', 'Membership Discount'), ('PACKAGE', 'Package Deal')], max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_nights', models.IntegerField(default=1)),
                ('min_advance_days', models.IntegerField(default=0, help_text='Minimum days in advance for early bird')),
                ('max_advance_days', models.IntegerField(blank=True, help_text='Maximum days in advance for last minute', null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('applicable_from', models.DateField(blank=True, help_text='Start date for applicable stay period', null=True)),
                ('applicable_until', models.DateField(blank=True, help_text='End date for applicable stay period', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority discounts are applied first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_room_types', models.ManyToManyField(blank=True, to='hotel.roomtype')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestLoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0, help_text='Total points earned over lifetime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='hotel.guest')),
            ],
            options={
                'verbose_name_plural': 'Guest Loyalty Points',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn Points'), ('REDEEM', 'Redeem Points'), ('EXPIRE', 'Points Expired'), ('ADJUST', 'Manual Adjustment'), ('REFUND', 'Refund Points')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.TextField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='hotel.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('voucher_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED_AMOUNT', 'Fixed Amount Discount'), ('FREE_NIGHT', 'Free Night Stay'), ('UPGRADE', 'Room Upgrade')], max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage vouchers', max_digits=12, null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Total number of times this voucher can be used', null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('usage_per_guest', models.IntegerField(default=1, help_text='Number of times a single guest can use this voucher')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum booking amount to use this voucher', max_digits=12)),
                ('min_nights', models.IntegerField(default=1, help_text='Minimum number of nights required')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('USED_UP', 'Used Up')], default='ACTIVE', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Public vouchers can be viewed by anyone')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_room_types', models.ManyToManyField(blank=True, help_text='Leave empty for all room types', to='hotel.roomtype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied', max_digits=12)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to='hotel.guest')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usage', to='hotel.payment')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages', to='hotel.reservation')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='hotel.voucher')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code', 'status'], name='hotel_vouch_code_8fc898_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['valid_from', 'valid_until'], name='hotel_vouch_valid_f_8b24bb_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherusage',
            index=models.Index(fields=['voucher', 'guest'], name='hotel_vouch_voucher_786f2a_idx'),
        ),
    ]
