# Generated by Django 5.2.7 on 2025-11-16 02:13

import apps.hotel.models.lost_found
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_alter_loyaltytransaction_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('HOUSEKEEPING', 'Housekeeping'), ('F&B', 'Food & Beverage'), ('MAINTENANCE', 'Maintenance'), ('FRONT_DESK', 'Front Desk'), ('ENGINEERING', 'Engineering'), ('LAUNDRY', 'Laundry')], max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current buffer quantity', max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Minimum buffer level', max_digits=10)),
                ('max_stock', models.DecimalField(decimal_places=2, default=100, help_text='Maximum buffer capacity', max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Physical storage location in department', max_length=100, null=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_buffers', to='hotel.inventoryitem')),
            ],
            options={
                'verbose_name': 'Department Inventory',
                'verbose_name_plural': 'Department Inventories',
                'ordering': ['department', 'inventory_item__name'],
                'unique_together': {('department', 'inventory_item')},
            },
        ),
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('report_type', models.CharField(choices=[('FOUND', 'Found Item'), ('LOST', 'Lost Item')], max_length=10)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('JEWELRY', 'Jewelry'), ('CLOTHING', 'Clothing'), ('DOCUMENTS', 'Documents'), ('MONEY', 'Money'), ('KEYS', 'Keys'), ('ACCESSORIES', 'Accessories'), ('TOILETRIES', 'Toiletries'), ('BOOKS', 'Books'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_STORAGE', 'In Storage'), ('CLAIMED', 'Claimed'), ('DISPOSED', 'Disposed'), ('RETURNED_TO_GUEST', 'Returned to Guest')], default='PENDING', max_length=20)),
                ('location_type', models.CharField(choices=[('ROOM', 'Guest Room'), ('LOBBY', 'Lobby'), ('RESTAURANT', 'Restaurant'), ('POOL', 'Pool Area'), ('GYM', 'Gym'), ('SPA', 'Spa'), ('PARKING', 'Parking'), ('HALLWAY', 'Hallway'), ('ELEVATOR', 'Elevator'), ('CONFERENCE', 'Conference Room'), ('OTHER', 'Other')], max_length=20)),
                ('specific_location', models.CharField(blank=True, help_text='Specific location details (e.g., under bed, in bathroom)', max_length=200)),
                ('reported_date', models.DateField(default=apps.hotel.models.lost_found.get_today)),
                ('reported_time', models.TimeField(auto_now_add=True)),
                ('found_date', models.DateField(blank=True, help_text='Date when item was actually found (may differ from report date)', null=True)),
                ('storage_location', models.CharField(blank=True, help_text='Where the item is currently stored in office/storage', max_length=200)),
                ('claimed_by_name', models.CharField(blank=True, max_length=200)),
                ('claimed_by_contact', models.CharField(blank=True, max_length=100)),
                ('claimed_date', models.DateField(blank=True, null=True)),
                ('claimed_time', models.TimeField(blank=True, null=True)),
                ('claim_notes', models.TextField(blank=True, help_text='Notes about claim verification process')),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_method', models.CharField(blank=True, help_text='How the item was disposed (donated, discarded, etc.)', max_length=200)),
                ('disposal_notes', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value in IDR', max_digits=12, null=True)),
                ('is_valuable', models.BooleanField(default=False, help_text='Mark if item is valuable (electronics, jewelry, money, documents)')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs for the item')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_verified_by', models.ForeignKey(blank=True, help_text='Staff member who verified and released the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claims', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, help_text='Guest who lost/found the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='hotel.guest')),
                ('handler', models.ForeignKey(blank=True, help_text='Office staff handling the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_lost_found_items', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='Staff member who reported the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lost_found_items', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, help_text='Related reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='hotel.reservation')),
                ('room', models.ForeignKey(blank=True, help_text='Room where item was found/lost (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='hotel.room')),
            ],
            options={
                'verbose_name': 'Lost and Found Item',
                'verbose_name_plural': 'Lost and Found Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'report_type'], name='hotel_losta_status_c77176_idx'), models.Index(fields=['reported_date'], name='hotel_losta_reporte_ae2c89_idx'), models.Index(fields=['guest'], name='hotel_losta_guest_i_269d46_idx'), models.Index(fields=['room'], name='hotel_losta_room_id_f6619b_idx'), models.Index(fields=['category'], name='hotel_losta_categor_8f5e65_idx')],
            },
        ),
        migrations.CreateModel(
            name='WakeUpCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(help_text='Guest name', max_length=200)),
                ('call_date', models.DateField(help_text='Date of the wake up call')),
                ('call_time', models.TimeField(help_text='Time for the wake up call')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the call was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Staff who completed the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wake_up_calls_completed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Staff who created the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wake_up_calls_requested', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, help_text='Associated reservation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wake_up_calls', to='hotel.reservation')),
                ('room', models.ForeignKey(help_text='Room number for the wake up call', on_delete=django.db.models.deletion.CASCADE, related_name='wake_up_calls', to='hotel.room')),
            ],
            options={
                'ordering': ['call_date', 'call_time'],
                'indexes': [models.Index(fields=['call_date', 'call_time'], name='hotel_wakeu_call_da_2805f2_idx'), models.Index(fields=['status', 'call_date'], name='hotel_wakeu_status_0bbb50_idx'), models.Index(fields=['room', 'call_date'], name='hotel_wakeu_room_id_87649a_idx')],
            },
        ),
    ]
